[theme]
primaryColor = "#F2B134"
font = "sans serif"

[theme.light]
primaryColor = "#B87800"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#17191C"

[theme.dark]
primaryColor = "#F2B134"
backgroundColor = "#17191C"
secondaryBackgroundColor = "#24272B"
textColor = "#F4F4F4"

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
